name: build-website

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  repository_dispatch:
    types: [doit]

  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: build-static-website
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install-node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install-dependencies
        run: npm install

      - name: generate
        run: |
          npm run repos:integrate
          npm run generate

      - name: deploy-with-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
